collections:
  authors:
    output: true
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

excerpt_separator: <!--more-->

plugins:
  - "jekyll-feed"

# ### site metadata ###
# title: My GitHub Projects

# repository: Crocboy-0501/Crocboy-0501.github.io
# author: Michael Currin

# ### Build settings ###

# url: https://crocboy-0501.github.io
# baseurl: ""