collections:
  authors:
    output: true
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

excerpt_separator: <!--more-->

plugins:
  - "jekyll-feed"



url: https://anwar.ink
baseurl: ""